// EventPulse style reminder: AI history is a quiet organizer proof sheet — short, comparable, and explicit about local-only persistence.
import { Check, Columns2, History, RotateCcw, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

export type AIDescriptionRecord = { id: string; description: string; tone: "professional" | "casual" | "exciting"; keywords: string; createdAt: string };
export const AI_HISTORY_KEY = "eventpulse-ai-description-history-v1";
export const AI_RESTORE_KEY = "eventpulse-pending-ai-restore-v1";
const readHistory = (): AIDescriptionRecord[] => { try { return JSON.parse(localStorage.getItem(AI_HISTORY_KEY) ?? "[]"); } catch { return []; } };

function VersionCard({ entry, label, onRestore }: { entry: AIDescriptionRecord; label: string; onRestore: () => void }) {
  return <article className="ticket-notch rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[var(--pulse-coral)]">{label}</p><p className="mt-2 font-display text-2xl font-semibold">{entry.tone} direction</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.12em] text-[var(--pulse-cobalt)]">{new Date(entry.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</span></div><div className="ticket-dashes mt-4 h-px text-border" /><p className="mt-4 text-sm leading-7 text-muted-foreground">{entry.description}</p><p className="mt-5 text-xs text-muted-foreground">Prompt signal: {entry.keywords}</p><button onClick={onRestore} className="button-press mt-5 inline-flex items-center gap-2 rounded-full bg-[var(--pulse-coral)] px-4 py-2.5 text-xs font-bold text-white"><RotateCcw size={14} /> Restore this version</button></article>;
}

export default function AIDescriptionHistoryDock() {
  const [location] = useLocation(); const [open, setOpen] = useState(false); const [history, setHistory] = useState<AIDescriptionRecord[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [compareId, setCompareId] = useState<string | null>(null);
  const refresh = () => setHistory(readHistory());
  useEffect(() => { refresh(); window.addEventListener("storage", refresh); window.addEventListener("eventpulse:ai-history-updated", refresh); return () => { window.removeEventListener("storage", refresh); window.removeEventListener("eventpulse:ai-history-updated", refresh); }; }, []);
  const selected = useMemo(() => history.find((entry) => entry.id === selectedId) ?? history[0], [history, selectedId]);
  const comparison = useMemo(() => history.find((entry) => entry.id === compareId) ?? history.find((entry) => entry.id !== selected?.id), [history, compareId, selected]);
  const restore = (entry: AIDescriptionRecord) => { localStorage.setItem(AI_RESTORE_KEY, JSON.stringify(entry)); window.dispatchEvent(new Event("eventpulse:open-description-draft")); setOpen(false); };
  if (location !== "/organizer") return null;
  return <><button onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-30 inline-flex items-center gap-2 rounded-full bg-[var(--pulse-ink)] px-4 py-3 text-xs font-bold text-white shadow-[0_14px_30px_rgba(32,35,42,.25)] transition hover:bg-[var(--pulse-cobalt)]"><History size={16} /> AI history {history.length > 0 && <span className="rounded-full bg-[var(--pulse-sun)] px-1.5 py-0.5 text-[10px] text-[var(--pulse-ink)]">{history.length}</span>}</button>{open && <div className="fixed inset-0 z-50 flex items-end bg-black/40 p-0 backdrop-blur-sm sm:items-center sm:justify-center sm:p-6" onMouseDown={(event) => event.target === event.currentTarget && setOpen(false)}><div className="ticket-notch max-h-[88vh] w-full max-w-6xl overflow-y-auto rounded-t-[2rem] bg-background shadow-2xl sm:rounded-[2rem]"><div className="flex items-start justify-between border-b border-border p-6"><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[var(--pulse-coral)]">Organizer proof sheet</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-[-.04em]">Compare the directions.</h2><p className="mt-2 text-sm text-muted-foreground">Choose a primary version and a comparison version, then restore either one into a fresh draft.</p></div><button onClick={() => setOpen(false)} className="rounded-full border border-border p-2 text-muted-foreground"><X size={17} /></button></div>{history.length ? <div className="p-6"><div className="flex flex-wrap gap-2">{history.map((entry) => <div key={entry.id} className="flex overflow-hidden rounded-full border border-border bg-card"><button onClick={() => setSelectedId(entry.id)} className={`px-3 py-2 text-[10px] font-bold uppercase tracking-[.1em] ${selected?.id === entry.id ? "bg-[var(--pulse-cobalt)] text-white" : "text-muted-foreground"}`}>{entry.tone}</button><button onClick={() => setCompareId(entry.id)} className={`border-l border-border px-2 text-[10px] ${comparison?.id === entry.id ? "bg-[var(--pulse-sun)] text-[var(--pulse-ink)]" : "text-muted-foreground"}`} aria-label={`Compare ${entry.tone} version`}><Columns2 size={13} /></button></div>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-2">{selected && <VersionCard entry={selected} label="Primary selection" onRestore={() => restore(selected)} />}{comparison && comparison.id !== selected?.id && <VersionCard entry={comparison} label="Compare against" onRestore={() => restore(comparison)} />}</div></div> : <div className="p-10 text-center"><History className="mx-auto text-[var(--pulse-cobalt)]" size={28} /><p className="mt-4 font-semibold">Nothing generated yet.</p><p className="mt-2 text-sm text-muted-foreground">Use the writing companion to make your first locally saved description version.</p></div>}</div></div>}</>;
}
